import { createConstants } from '../../utils';

/*export default createConstants(
  'REQUEST_SIGN_IN',
  'REQUEST_AUTH_TOKEN',
  'RECEIVE_AUTH_TOKEN',
  'RECEIVE_AUTH_TOKEN_FAILED',

  'SIGN_IN',
  'SIGN_OUT',
  'REGISTER'
);*/

export default {
  'REQUEST_SIGN_IN': 'REQUEST_SIGN_IN',
  'REQUEST_AUTH_TOKEN': 'REQUEST_AUTH_TOKEN',
  'RECEIVE_AUTH_TOKEN': 'RECEIVE_AUTH_TOKEN',
  'RECEIVE_AUTH_TOKEN_FAILED': 'RECEIVE_AUTH_TOKEN_FAILED',

  'SIGN_IN': 'SIGN_IN',
  'SIGN_OUT': 'SIGN_OUT',
  'REGISTER': 'REGISTER'
};
